spring.application.name=techstack-explorer

server.port=8080

# CognoDB / Neo4j
cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME}
cognodb.password=${COGNODB_PASSWORD}

# JSON
spring.jackson.serialization.indent-output=true